name: Check for broken links on site

on:
  workflow_run:
    workflows: [Deploy site]
    types: [completed]

permissions:
  actions: read
  contents: read

jobs:
  check-links-on-site:
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-a-workflow-based-on-the-conclusion-of-another-workflow
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    # available images: https://github.com/actions/runner-images#available-images
    runs-on: ubuntu-latest
    steps:
      - name: Download built site artifact 📦
        uses: actions/download-artifact@v4
        with:
          name: site-build
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ github.token }}
          path: _site
      - name: Link Checker 🔗
        uses: lycheeverse/lychee-action@v1.9.0
        with:
          fail: true
          # only check local links
          args: --offline --remap '_site(/?.*)/assets/(.*) _site/assets/$2' --verbose --no-progress '_site/**/*.html'
